<a href="https://colab.research.google.com/github/0414JUYOUNG/python/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_k%EC%B5%9C%EA%B7%BC%EC%A0%91%EC%9D%B4%EC%9B%83%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98_%EA%B0%95%EC%9D%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#붓꽃 데이터
iris = pd.read_csv('https://bit.ly/3tjyEaw') #데이터 타입 = 데이터 프레임

In [ ]:
iris.head()

caseno  SepalLength  SepalWidth  PetalLength  PetalWidth Species
0       1          5.1         3.5          1.4         0.2  setosa
1       2          4.9         3.0          1.4         0.2  setosa
2       3          4.7         3.2          1.3         0.2  setosa
3       4          4.6         3.1          1.5         0.2  setosa
4       5          5.0         3.6          1.4         0.2  setosa

In [ ]:
iris.tail()

caseno  SepalLength  SepalWidth  PetalLength  PetalWidth    Species
145     146          6.7         3.0          5.2         2.3  virginica
146     147          6.3         2.5          5.0         1.9  virginica
147     148          6.5         3.0          5.2         2.0  virginica
148     149          6.2         3.4          5.4         2.3  virginica
149     150          5.9         3.0          5.1         1.8  virginica

In [ ]:
iris.describe()

caseno  SepalLength  SepalWidth  PetalLength  PetalWidth
count  150.000000   150.000000  150.000000   150.000000  150.000000
mean    75.500000     5.843333    3.057333     3.758000    1.199333
std     43.445368     0.828066    0.435866     1.765298    0.762238
min      1.000000     4.300000    2.000000     1.000000    0.100000
25%     38.250000     5.100000    2.800000     1.600000    0.300000
50%     75.500000     5.800000    3.000000     4.350000    1.300000
75%    112.750000     6.400000    3.300000     5.100000    1.800000
max    150.000000     7.900000    4.400000     6.900000    2.500000

In [ ]:
print(iris['Species'])

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object


In [ ]:
print(np.unique(iris['Species']))

['setosa' 'versicolor' 'virginica']


Date 와 Target분리

In [ ]:
iris_input = iris[['SepalWidth', 'SepalLength', 'PetalWidth','PetalLength']] #4개의 값을 list로 출력

print(iris_input) #이것도 데이터 프레임 (판다스에서 받아온 데이터를 받아오기때문에)

     SepalWidth  SepalLength  PetalWidth  PetalLength
0           3.5          5.1         0.2          1.4
1           3.0          4.9         0.2          1.4
2           3.2          4.7         0.2          1.3
3           3.1          4.6         0.2          1.5
4           3.6          5.0         0.2          1.4
..          ...          ...         ...          ...
145         3.0          6.7         2.3          5.2
146         2.5          6.3         1.9          5.0
147         3.0          6.5         2.0          5.2
148         3.4          6.2         2.3          5.4
149         3.0          5.9         1.8          5.1

[150 rows x 4 columns]


In [ ]:
iris_target = iris['Species'] #하나의 값만 출력
print(iris_target)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: Species, Length: 150, dtype: object


Date 와 Target분리
Dateframe을 Numpy ndarray로 변환

In [ ]:
iris_input = iris_input.to_numpy()
print(iris_input) # 넘파이는 행열처럼 생김 4행 150열 배열로보면 2차배열 [[]] 

[[3.5 5.1 0.2 1.4]
 [3.  4.9 0.2 1.4]
 [3.2 4.7 0.2 1.3]
 [3.1 4.6 0.2 1.5]
 [3.6 5.  0.2 1.4]
 [3.9 5.4 0.4 1.7]
 [3.4 4.6 0.3 1.4]
 [3.4 5.  0.2 1.5]
 [2.9 4.4 0.2 1.4]
 [3.1 4.9 0.1 1.5]
 [3.7 5.4 0.2 1.5]
 [3.4 4.8 0.2 1.6]
 [3.  4.8 0.1 1.4]
 [3.  4.3 0.1 1.1]
 [4.  5.8 0.2 1.2]
 [4.4 5.7 0.4 1.5]
 [3.9 5.4 0.4 1.3]
 [3.5 5.1 0.3 1.4]
 [3.8 5.7 0.3 1.7]
 [3.8 5.1 0.3 1.5]
 [3.4 5.4 0.2 1.7]
 [3.7 5.1 0.4 1.5]
 [3.6 4.6 0.2 1. ]
 [3.3 5.1 0.5 1.7]
 [3.4 4.8 0.2 1.9]
 [3.  5.  0.2 1.6]
 [3.4 5.  0.4 1.6]
 [3.5 5.2 0.2 1.5]
 [3.4 5.2 0.2 1.4]
 [3.2 4.7 0.2 1.6]
 [3.1 4.8 0.2 1.6]
 [3.4 5.4 0.4 1.5]
 [4.1 5.2 0.1 1.5]
 [4.2 5.5 0.2 1.4]
 [3.1 4.9 0.2 1.5]
 [3.2 5.  0.2 1.2]
 [3.5 5.5 0.2 1.3]
 [3.6 4.9 0.1 1.4]
 [3.  4.4 0.2 1.3]
 [3.4 5.1 0.2 1.5]
 [3.5 5.  0.3 1.3]
 [2.3 4.5 0.3 1.3]
 [3.2 4.4 0.2 1.3]
 [3.5 5.  0.6 1.6]
 [3.8 5.1 0.4 1.9]
 [3.  4.8 0.3 1.4]
 [3.8 5.1 0.2 1.6]
 [3.2 4.6 0.2 1.4]
 [3.7 5.3 0.2 1.5]
 [3.3 5.  0.2 1.4]
 [3.2 7.  1.4 4.7]
 [3.2 6.4 1.5 4.5]
 [3.1 6.9 1.

In [ ]:
iris_target = iris_target.to_numpy()
print(iris_target)

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

In [ ]:
print(iris_input.shape, iris_target.shape)

(150, 4) (150,)


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_input, test_input, train_target, test_target = \ # \줄바꿈할때 연결되어있다는 의미 트레이닝(학습)용 테스트용으로 분류
  train_test_split(iris_input, iris_target,test_size=0.2, random_state=21) #섞기위해서 랜덤사용해야함ramdom_state

In [ ]:
print(train_input.shape, train_target.shape)

(120, 4) (120,)


In [ ]:
print(test_input.shape, test_target.shape)

(30, 4) (30,)


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ss = StandardScaler() # 표준편자 구하는거
ss.fit(train_input) # 표준편자 얼마인지 계산해주는거 fit 
train_scaled = ss.transform(train_input) # 실제로 데이터를 변환해주는 scaled
test_scaled = ss.transform(test_input)

In [ ]:
print(train_scaled) #값을 표준화함

[[-1.80610292 -1.61401413 -1.19487306 -1.41372184]
 [ 1.77822482  2.3988912   0.99716025  1.45402018]
 [ 0.34449372  0.03835865  0.73927398  0.55433641]
 [ 1.77822482 -0.90585436 -1.3238162  -1.24503114]
 [-0.61132701  0.39243854  0.73927398  0.55433641]
 [-0.61132701  0.74651842  0.35244457  0.44187594]
 [ 0.82240409  0.15638528  0.48138771  0.3856457 ]
 [-0.61132701 -0.07966797  1.5129328   0.72302711]
 [-0.13341664 -1.73204075 -1.3238162  -1.41372184]
 [-0.85028219 -0.07966797  0.86821712  0.72302711]
 [-0.13341664  0.03835865  0.73927398  0.72302711]
 [ 0.82240409  0.51046516  1.5129328   1.00417829]
 [-1.32819256 -0.1976946   0.99716025  0.66679688]
 [-0.37237183  0.39243854  0.0945583   0.27318523]
 [ 0.10553854  1.21862493  1.38398966  0.72302711]
 [ 1.06135927 -0.43374785 -1.3238162  -1.41372184]
 [ 1.30031445 -1.14190762 -1.45275934 -1.35749161]
 [-0.13341664 -1.85006738 -1.45275934 -1.52618231]
 [-2.0450581   0.39243854  0.35244457  0.3856457 ]
 [ 0.82240409 -1.25993425 -1.32

k-최근접 이웃 다중분류
(학습용과 테스트용 분류)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 